### ISSUE TITLE
Why should I use gkroam.el over org-roam?

### ISSUE THREAD

**Issue by j-steinbach** [Kinneyzhang/gkroam.el#13]
This looks cool, but why should I use it over [org-roam](https://github.com/org-roam/org-roam/)? What are the differences?

**Comment by Kinneyzhang** [comment]
I cannot tell you the differences between the two because I didn't use org-roam. Maybe you could look at the gif demos in docs or try to use gkroam to know the differences. My ideas of gkroam comes from [casouri](https://github.com/casouri)'s [bklink.el](https://github.com/casouri/lunarymacs/blob/master/site-lisp/bklink.el) and [Roam Research](http://roamresearch.com).

**Comment by QiangF** [comment]
In my opinion, org-roam is too big for small collection of files.
