### ISSUE TITLE
orgmode throw an error when using gkroam-daily

### ISSUE THREAD

**Issue by zbelial** [Kinneyzhang/gkroam.el#19]
I've encountered an error when trying out `gkroam-daily`, here is the backtrace:
```elisp
* org-check-agenda-file("/Notes/Org/gkroam/20201007103043.org")
  org-agenda-prepare-buffers(("/Notes/Org/gkroam/20201007103043.org"))
  org-map-entries(#f(compiled-function () #<bytecode 0x158418c1fff5>))
  gkroam-heading-id-pairs()
  gkroam-build-page-cache()
  #f(compiled-function () #<bytecode 0x158418c24abd>)()
  run-hooks(before-save-hook)
  basic-save-buffer(nil)
  save-buffer()
  gkroam-new("10月 07, 2020")
  gkroam-find("10月 07, 2020")
  gkroam-daily()
  funcall-interactively(gkroam-daily)
```

If I were right, it's because `gkroam-build-page-cache`, which calls `org-check-agenda-file` indirectly, runs in `before-save-hook`, where the daily file has not been saved to disk so the `file-exists-p` check in `org-check-agenda-file` fails. 

I've tested this, but maybe putting `gkroam-build-page-cache` in `after-save-hook` can solve this problem?

**Comment by Kinneyzhang** [comment]
Wow, thanks! Honestly, I have tolerated this question for quite a period of time. Every time I create a new gkroam page used ```gkroam-daily``` or ```gkroam-find``` , emacs will give me a prompt "None existence of agenda file ... .org ... Abort or Remove from agenda list" and I have to cancel this manually. Sadly, I cannot work around this because I can't find out the reason.

The situation I described is just like what you mentioned but not a error. Now, I have found out why this warning or error would  throw out from your description. So, thanks a lot!

I have tested, use ```after-save-hook``` will take care of it.

**Comment by zbelial** [comment]
Glad to help you( and other users), and sorry that I didn't give a precise description: It's a message, not an error, as you mentioned. And when I said "I've tested this" in the first post, I meant "I've not tested this" :(

Since that you have fixed the problem, I'll close this issue.
